apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: my-web-app-service-entry
  namespace: istio-poc
spec:
  hosts:
  - ec2-3-125-207-155.eu-central-1.compute.amazonaws.com
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL